apiVersion: 1
datasources:
- name: influxdb
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: influx_db
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: password