apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  loadBalancerIP: 172.17.0.5
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer