apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  loadBalancerIP: 172.17.0.11
  ports:
    - port: 5050
      targetPort: 80
      name: wp-server
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer