apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  loadBalancerIP: 172.17.0.3
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: sshd
  selector:
    app: nginx
  type: LoadBalancer