apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana-serv
        livenessProbe:
          exec:
            command:
              - /bin/ash
              - -c
              - 'pgrep telegraf'
          initialDelaySeconds: 10
          periodSeconds: 5