apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  loadBalancerIP: 172.17.0.12
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana-serv
  selector:
    app: grafana
  type: LoadBalancer 