apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never
        env:
        - name: FTPS_USER
          value: admin
        - name: FTPS_PASSWORD
          value: truc
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 20
          name: ftp
        - containerPort: 32099
          name: pasv-min
        - containerPort: 32100
          name: pasv-max
        livenessProbe:
          exec:
            command:
              - pgrep telegraf
          initialDelaySeconds: 10
          periodSeconds: 5              