apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  loadBalancerIP: 172.17.0.8
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 31000
    targetPort: 31000
    name: ftps-data
  selector:
    app: ftps
